#!/bin/bash
# Quick Reference - InnerBright Deployment Nov 18, 2025

echo "==================================="
echo "InnerBright.vn - Quick Reference"
echo "==================================="
echo ""
echo "🌐 Site: https://innerbright.vn"
echo "🔐 Admin Login: https://innerbright.vn/auth/login"
echo "📊 Health: http://116.118.48.208:3005/api/health"
echo ""
echo "👤 Credentials:"
echo "   Email: admin@example.com"
echo "   Password: admin123"
echo ""
echo "🔑 Google OAuth:"
echo "   Email: katachanneloffical@gmail.com"
echo "   (Sau khi login lần đầu, cần promote lên admin)"
echo ""
echo "==================================="
echo "Common Commands"
echo "==================================="
echo ""
echo "# 1. Check container status"
echo "ssh root@116.118.48.208 'docker ps | grep innerbright'"
echo ""
echo "# 2. View logs"
echo "ssh root@116.118.48.208 'docker logs innerbright-web -f'"
echo ""
echo "# 3. Check database users"
echo "ssh root@116.118.48.208 \"docker exec innerbright-postgres psql -U postgres -d innerv2core -c 'SELECT email, role FROM users;'\""
echo ""
echo "# 4. Promote Google user to admin"
echo "ssh root@116.118.48.208 \"docker exec innerbright-postgres psql -U postgres -d innerv2core -c \\\"UPDATE users SET role = 'admin' WHERE email = 'katachanneloffical@gmail.com';\\\"\""
echo ""
echo "# 5. Restart container"
echo "ssh root@116.118.48.208 'cd /var/www/innerbright && docker-compose restart innerbright-web'"
echo ""
echo "# 6. Check health"
echo "curl http://116.118.48.208:3005/api/health"
echo ""
echo "==================================="
echo "Deployment Info"
echo "==================================="
echo "Date: 18 Nov 2025, 21:46 ICT"
echo "Image: innerbright-web:latest"
echo "Container: innerbright-web"
echo "Status: ✅ Running & Healthy"
echo ""
