#!/bin/bash
# Quick Fix Summary for OAuthAccountNotLinked Error

echo "=========================================="
echo "🔧 OAUTH ACCOUNT NOT LINKED - FIXED"
echo "=========================================="
echo ""
echo "📋 Summary:"
echo "  Problem: admin@example.com couldn't login with password"
echo "  Error: OAuthAccountNotLinked"
echo "  Cause: Google OAuth account was linked to same email"
echo "  Fix: Deleted OAuth account link from database"
echo ""
echo "✅ Fix Applied:"
echo "  1. Removed Google OAuth link from accounts table"
echo "  2. Kept credentials (email + password) intact"
echo "  3. Restarted container to clear session cache"
echo ""
echo "🔐 Test Credentials:"
echo "  URL: https://innerbright.vn/auth/login"
echo "  Email: admin@example.com"
echo "  Password: admin123"
echo ""
echo "📊 Current Database State:"
ssh root@116.118.48.208 "docker exec innerbright-postgres psql -U postgres -d innerv2core -t -c \"SELECT '  Email: ' || email || '\n  Role: ' || role || '\n  Verified: ' || CASE WHEN \\\"emailVerified\\\" IS NOT NULL THEN 'Yes' ELSE 'No' END || '\n  Has Password: ' || CASE WHEN password IS NOT NULL THEN 'Yes' ELSE 'No' END || '\n  OAuth Accounts: ' || COALESCE((SELECT COUNT(*)::text FROM accounts WHERE \\\"userId\\\" = u.id), '0') FROM users u WHERE email = 'admin@example.com';\""
echo ""
echo "🚀 Status: READY TO TEST"
echo "=========================================="
echo ""
echo "📝 Quick Commands:"
echo ""
echo "# View logs"
echo "ssh root@116.118.48.208 'docker logs innerbright-web -f'"
echo ""
echo "# Check user status"
echo "ssh root@116.118.48.208 \"docker exec innerbright-postgres psql -U postgres -d innerv2core -c 'SELECT email, role FROM users WHERE email = \\\"admin@example.com\\\";'\""
echo ""
echo "# Restart if needed"
echo "ssh root@116.118.48.208 'cd /var/www/innerbright && docker-compose restart innerbright-web'"
echo ""
