#!/bin/bash
# Test Cookie Fix with Enhanced Logging

echo "============================================="
echo "🍪 Cookie Fix Deployed - Testing Guide"
echo "============================================="
echo ""
echo "✅ Changes Applied:"
echo "  1. Added proper cookies configuration"
echo "  2. Fixed sessionToken cookie settings"
echo "  3. Added extensive logging to auth callbacks"
echo ""
echo "🧪 Testing Steps:"
echo ""
echo "Step 1: Clear ALL Browser Data"
echo "-----------------------------------------------"
echo "VERY IMPORTANT - Must clear everything!"
echo ""
echo "Chrome:"
echo "  1. F12 > Application > Storage"
echo "  2. Click 'Clear site data'"
echo "  3. Confirm all boxes checked"
echo ""
echo "Firefox:"
echo "  1. F12 > Storage"
echo "  2. Right-click on innerbright.vn"
echo "  3. Delete All"
echo ""
echo "Or just use Incognito/Private window"
echo ""
echo "Step 2: Monitor Logs"
echo "-----------------------------------------------"
echo "Open a second terminal and run:"
echo "  ssh root@116.118.48.208 'docker logs innerbright-web -f'"
echo ""
echo "Step 3: Login"
echo "-----------------------------------------------"
echo "  URL: https://innerbright.vn/auth/login"
echo "  Email: admin@example.com"
echo "  Password: admin123"
echo ""
echo "Step 4: Check Logs Output"
echo "-----------------------------------------------"
echo "You should see:"
echo ""
echo "[Auth] signIn callback: {"
echo "  provider: 'credentials',"
echo "  userEmail: 'admin@example.com',"
echo "  userId: '...',"
echo "  userRole: 'admin'"
echo "}"
echo ""
echo "[Auth] JWT callback - user object: {"
echo "  userId: '...',"
echo "  userEmail: 'admin@example.com',"
echo "  userRole: 'admin'"
echo "}"
echo ""
echo "[Auth] JWT callback - DB user: {"
echo "  dbUserId: '...',"
echo "  dbUserRole: 'admin',"
echo "  dbUserVerified: true"
echo "}"
echo ""
echo "[Auth] JWT callback - final token: {"
echo "  tokenId: '...',"
echo "  tokenRole: 'admin',"
echo "  tokenEmail: 'admin@example.com'"
echo "}"
echo ""
echo "Step 5: Try Access /admin"
echo "-----------------------------------------------"
echo "After login, go to: https://innerbright.vn/admin"
echo ""
echo "Should see in logs:"
echo "[Middleware] Admin access attempt: {"
echo "  pathname: '/admin',"
echo "  hasToken: true,"
echo "  email: 'admin@example.com',"
echo "  role: 'admin',"
echo "  tokenKeys: [...]"
echo "}"
echo ""
echo "[Middleware] Role check: {"
echo "  userRole: 'admin',"
echo "  allowedRoles: ['admin', 'manager', 'editor'],"
echo "  isAllowed: true"
echo "}"
echo ""
echo "✅ Expected Result:"
echo "-----------------------------------------------"
echo "  - Login successful"
echo "  - Cookie set properly"
echo "  - Token contains role='admin'"
echo "  - /admin page loads"
echo "  - No redirect loops"
echo ""
echo "❌ If Still Fails:"
echo "-----------------------------------------------"
echo "  1. Check cookie in browser DevTools:"
echo "     - Name: __Secure-next-auth.session-token (production)"
echo "     - Domain: innerbright.vn"
echo "     - Path: /"
echo "     - HttpOnly: true"
echo "     - Secure: true"
echo ""
echo "  2. Share the FULL log output from login attempt"
echo ""
echo "============================================="
echo "Starting Log Monitor..."
echo "============================================="
echo ""

# Monitor logs
ssh root@116.118.48.208 'docker logs innerbright-web -f --tail 0' &
LOG_PID=$!

echo "Logs monitoring... (PID: $LOG_PID)"
echo ""
echo "NOW:"
echo "  1. Clear browser cookies"
echo "  2. Go to https://innerbright.vn/auth/login"
echo "  3. Login with admin@example.com / admin123"
echo "  4. Watch logs above"
echo ""
echo "Press Ctrl+C when done"
echo ""

wait $LOG_PID
